#!/usr/bin/env bash

# Depends: Mugshot
# Written by manilarome

awesome_dir="${HOME}/.config/awesome/"
user_profile_dir="${awesome_dir}themes/default/icons/system/"

accountsservice_user_icons="/var/lib/AccountsService/icons/${USER}"

# Check if user image "user.png" exists. If so, then the image in
# AccountsService directory or the default image will not be used.
if [ -f "${user_profile_dir}user.png" ];
then
	printf "${user_profile_dir}user.png"
	exit;
else
	if [ -f "${accountsservice_user_icons}" ];
	then
		cp "${accountsservice_user_icons}" "${user_profile_dir}user.png"
		printf "${user_profile_dir}user.png"
		exit;
	else
		printf "default"
		exit;
	fi
fi
