#!/bin/sh

B='#282828FF'  # blank
C='#ffffffFF'  # clear ish
D='#0A7ACAFF'  # default
T='#569cd6FF'  # text
W='#F44747FF'  # wrong
V='#FFAF00FF'  # verifying
VT='#608B4EFF'
HL='#FA4616FF'


i3lock                          \
    --radius 60                 \
    --ind-pos="w/2:h/2"         \
    --time-pos="w/2:h/2-200"    \
    --date-pos="w/2:h/2-160"    \
    --greeter-pos="w/2:h/2"     \
    --insidever-color=$B        \
    --ringver-color=$V          \
    --ring-width=6              \
    \
    --insidewrong-color=$W      \
    --ringwrong-color=$C        \
    \
    --inside-color=$B           \
    --ring-color=$D             \
    --line-color=$B             \
    --separator-color=$D        \
    \
    --verif-color=$VT           \
    --wrong-color=$C            \
    --time-color=$C             \
    --date-color=$C             \
    --layout-color=$T           \
    --keyhl-color=$HL           \
    --bshl-color=$W             \
    \
    --screen 1                  \
    --blur 5                    \
    --clock                     \
    --indicator                 \
    --date-str="%A, %B %d"      \
    --wrong-text="incorrect!"   \
    --verif-text="verifying"    \
    --time-size=75              \
    --date-size=30              \
    --verif-size=20             \
    --wrong-size=20             \
